# fly.toml app configuration file generated for hello-23e-bw on 2026-10-06T03:15:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-23e-bw'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'ghazi'
  destination = '/ghazi'

[http_service]
  internal_port = 2222
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 65536
