# fly.toml app configuration file generated for ghazian on 2026-08-25T17:26:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ghazian'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'ghazi'
  destination = '/ghazi'
  initial_size = '320gb'

[[services]]
  protocol = 'tcp'
  internal_port = 2222

  [[services.ports]]
    port = 2222

[[vm]]
  memory = '32gb'
  cpu_kind = 'shared'
  cpus = 16
  memory_mb = 32768

  
